Prova.EnContact.UIWeb/Controllers/RecadosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Prova.EnContact.Compartilhado.Constantes;
using Prova.EnContact.Compartilhado.Utilitarios;
using Prova.EnContact.Interfaces.Interfaces.Modelos;
using Prova.EnContact.Interfaces.Interfaces.Servicos;
using Prova.EnContact.Modelos.Modelos;

namespace Prova.EnContact.UIWeb.Controllers
{
    public class RecadosController : Controller
    {
        [TempData]
        public string MensagemDeStatus { get; set; }

        private const string chavePermitirDataRetroativa = "ConfiguracoesDaAplicacao:PermitirExibirCampoDataDoRecado";
        protected readonly IRecadoServico<Recado> _recadoServico;
        protected readonly IAgrupamentoServico<Agrupamento> _agrupamentoServico;
        private readonly bool _permitirExibirCampoDataDoRecadoParaDataRetroativa;

        public RecadosController(IServiceProvider services)
        {
            _recadoServico = services.GetRequiredService<IRecadoServico<Recado>>();
            _agrupamentoServico = services.GetRequiredService<IAgrupamentoServico<Agrupamento>>();
            _permitirExibirCampoDataDoRecadoParaDataRetroativa = services.ObtenhaBoolDasConfiguracoes(chavePermitirDataRetroativa);
        }

        public ActionResult Cadastrar()
        {
            ViewData["Titulo"] = ConstantesPalavras.CADASTRAR_RECADO;
            ViewData["Mensagem"] = MensagemDeStatus;
            ViewData["PermitirDataRetroativa"] = _permitirExibirCampoDataDoRecadoParaDataRetroativa;
            return View(new Recado());
        }

        public ActionResult Editar(Guid id)
        {
            var recado = _recadoServico.ObtenhaPorId(id);

            ViewData["Titulo"] = ConstantesPalavras.EDITAR_RECADO;
            ViewData["PermitirDataRetroativa"] = _permitirExibirCampoDataDoRecadoParaDataRetroativa;
            return View(recado);
        }

        [HttpPost]
        public ActionResult Editar(Recado recado)
        {
            try
            {
                ViewData["Titulo"] = ConstantesPalavras.EDITAR_RECADO;

                if (ModelState.IsValid)
                {
                    _agrupamentoServico.EditarRecado(recado);
                    MensagemDeStatus = ConstantesPalavras.RECADO_EDITADO_SUCESSO;
                    return RedirectToAction(nameof(VerRecados));
                }

                return View(nameof(Editar), recado);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(string.Format(ConstantesPalavras.ERRO, ex.Message));
                throw;
            }
        }

        [HttpPost]
        public ActionResult Cadastrar(Recado recado)
        {
            try
            {
                ViewData["Titulo"] = ConstantesPalavras.CADASTRAR_RECADO;

                if (ModelState.IsValid)
                {
                    _agrupamentoServico.SalvarRecado(recado);
                    MensagemDeStatus = ConstantesPalavras.RECADO_CADASTRADO_SUCESSO;
                    return RedirectToAction(nameof(Cadastrar));
                }

                return View(nameof(Cadastrar), recado);
            }
            catch(Exception ex)
            {
                Debug.WriteLine(string.Format(ConstantesPalavras.ERRO, ex.Message));
                throw;
            }
        }

        public ActionResult VerRecados()
        {
            try
            {
                ViewData["Mensagem"] = MensagemDeStatus;
                ViewData["Titulo"] = ConstantesPalavras.VER_RECADOS;
                var recados = _agrupamentoServico.ObtenhaTodos();
                return View(recados);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(string.Format(ConstantesPalavras.ERRO, ex.Message));
                throw;
            }
        }
    }
}

Prova.EnContact.UIWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Titulo"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/Layout.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/Layout.css" />
    </environment>

    @RenderSection("StyleSheets", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@ConstantesPalavras.ENCONTACT</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Recados" asp-action="VerRecados">@ConstantesPalavras.VER_RECADOS</a></li>
                    <li><a asp-area="" asp-controller="Recados" asp-action="Cadastrar">@ConstantesPalavras.CADASTRAR_RECADO</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>